apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: MGU1YzhjZTQ1NjQxMTZmODlhNWJhMmIzMjFjNmU4ZWFlY2RkMGMxOWZjY2E1ZjcwN2FkZGE0YjVjNmU4YThlZjVjY2U2OWI0ZGFjNmM0ZDVhNzhhN2JmNTI5YzliYzE4OTFlZDdlOTlhODk4M2ZiZGM0OGM3ZDYxZDM3ZjhjMTk=
